services:
  web:
    build: .
    deploy:
      replicas: 3 
    expose:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web